### PR TITLE
Python Runner

### PR DESCRIPTION
**Pull request by enzanki-ars**

### CODE REVIEW

**Comment by enzanki-ars** [comment]
What?

**Comment by jacobsims** [comment]
You fixed it.

**Comment by enzanki-ars** [comment]
Nope....

```
java.io.FileNotFoundException: /home/ubuntu/battles/results/melee/darby.txt (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at net.sf.robocode.core.RobocodeMain.printResultsData(RobocodeMain.java:332)
    at net.sf.robocode.core.RobocodeMain.access$200(RobocodeMain.java:47)
    at net.sf.robocode.core.RobocodeMain$BattleObserver.onBattleCompleted(RobocodeMain.java:364)
    at net.sf.robocode.battle.events.BattleEventDispatcher.onBattleCompleted(BattleEventDispatcher.java:58)
    at net.sf.robocode.battle.Battle.finalizeBattle(Battle.java:323)
    at net.sf.robocode.battle.BaseBattle.run(BaseBattle.java:212)
    at java.lang.Thread.run(Thread.java:745)

java.io.FileNotFoundException: /home/ubuntu/battles/results/melee/darby.br (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
    at net.sf.robocode.recording.RecordManager.saveRecord(RecordManager.java:309)
    at net.sf.robocode.core.RobocodeMain$BattleObserver.onBattleCompleted(RobocodeMain.java:367)
    at net.sf.robocode.battle.events.BattleEventDispatcher.onBattleCompleted(BattleEventDispatcher.java:58)
    at net.sf.robocode.battle.Battle.finalizeBattle(Battle.java:323)
    at net.sf.robocode.battle.BaseBattle.run(BaseBattle.java:212)
    at java.lang.Thread.run(Thread.java:745)
```

Oops

**Comment by jacobsims** [comment]
You fixed the issue with a previous commit. But yeah. You'll have to makedirs() on the dirname.

**Comment by enzanki-ars** [comment]
I have never learned....

**Comment by jacobsims** [comment]
dirname.

**Comment by enzanki-ars** [comment]
Once it works, I will expand the battles and the runners available.

Should the code be `os.makedirs(os.path.expanduser('~/battles/results/' + battle))`?
https://docs.python.org/2/library/os.html#os.makedirs

**Comment by jacobsims** [comment]
Replace `battle` with `os.path.dirname(battle)`

**Comment by jacobsims** [comment]
It should work for now though, so dont cancel build

**Comment by enzanki-ars** [comment]
Me fool.

**Comment by enzanki-ars** [comment]
Maybe not...?

**Pull request merged**
